- name: Base set up
  hosts: all
  #Выполнять действия от root-пользователя
  become: yes
  tasks:
  #Установка текстового редактора nano и chrony
  - name: install softs
    ansible.builtin.yum:
      name:
        - nano
        - chrony
      state: present
      update_cache: true
  
  #Отключение firewalld и удаление его из автозагрузки
  - name: disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false

  #Отключение SElinux из автозагрузки
  #Будет применено после перезагрузки
  - name: disable SElinux
    selinux:
      policy: targeted
      state: disabled
  
  #Отключение SElinux до перезагрузки
  - name: disable SElinux now
    shell: setenforce 0
    ignore_errors: yes

  #Установка временной зоны
  - name: Set up timezone
    timezone:
      name: "Asia/Yekaterinburg"
  
  #Запуск службы Chrony, добавление её в автозагрузку
  - name: enable chrony
    service:
      name: chronyd
      state: restarted
      enabled: true
  
  #Копирование файла /etc/hosts c правами root:root 0644
  - name: change /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644


#### Конфигурирование сервера ###

- name: Config IPA Server
  hosts: ipa_server
  become: yes
  tasks:

# Обновляем nss
  - name: Upgrade nss
    ansible.builtin.yum:
      name: 'nss'
      state: latest


#Установка сервера Freeipa
  - name: install packages
    ansible.builtin.yum:
      name:
        - ipa-server
        - ipa-server-dns  

#Удаление конфига сервера Freeipa при необходимости
  #- name: delete freeipa-server config
  #  command: |
  #    ipa-server-install -U \
  #    --uninstall \

#Конфигурирование freeipa сервера
  - name: configure freeipa
    command: |
      ipa-server-install -U \
      -r OTUS.LAN \
      -n otus.lan \
      -p otus2023 \
      -a otus2023 \
      --hostname=ipa.otus.lan \
      --ip-address=192.168.57.10 \
      --mkhomedir \
      --no-ntp \


### Конфигурирование клиентов ###

- name: Config Clients
  hosts: ipa_client1, ipa_client2
  become: yes
  tasks:

# Обновляем nss
  - name: Upgrade nss client
    ansible.builtin.yum:
      name: 'nss'
      state: latest

#Установка клиента Freeipa
  - name: install module ipa-client
    ansible.builtin.yum:
      name:
        - freeipa-client
      state: present
      update_cache: true

#Запуск скрипта добавления хоста к серверу
  - name: configure ipa-client
    command: |
      ipa-client-install -U \
      --principal admin@OTUS.LAN \
      --password otus2023 \
      --server ipa.otus.lan \
      --domain otus.lan \
      --realm OTUS.LAN \
      --mkhomedir \
      --force-join
