---
# tasks file for auditd-web
    - name: в конец файла /etc/audit/rules.d/audit.rules добавляем правило, которое будет отслеживать изменения в конфигруации nginx
      ansible.builtin.blockinfile:
        path: /etc/audit/rules.d/audit.rules
        block: |
      
         -w /etc/nginx/nginx.conf -p wa -k nginx_conf
         -w /etc/nginx/default.d/ -p wa -k nginx_conf
             
    
    - name: Install audispd-plugins (устанавливаем пакет audispd-plugins)
      ansible.builtin.yum:
        name: audispd-plugins
        state: present
    
    - name: В name_format указываем HOSTNAME, чтобы в логах на удаленном сервере отображалось имя хоста
      ansible.builtin.replace:
        path: "/etc/audit/auditd.conf"
        regexp: '^name_format = NONE'
        replace: 'name_format = HOSTNAME'
    
    - name: В файле /etc/audisp/plugins.d/au-remote.conf меняем параметр active на yes
      ansible.builtin.replace:
        path: "/etc/audisp/plugins.d/au-remote.conf"
        regexp: 'active = no'
        replace: 'active = yes'


    - name: В файле /etc/audisp/audisp-remote.conf указываем адрес сервера и порт, на который будут отправляться логи
      ansible.builtin.replace:
        path: "/etc/audisp/audisp-remote.conf"
        regexp: 'remote_server = '
        replace: 'remote_server = 192.168.50.15'


    - name: restart auditd (перезапускаем службу auditd)
      ansible.builtin.shell: service auditd restart